const MusicGenre = {
  ROCK: 'Rock',
  POP: 'Pop',
  METAL: 'Metal',
  PUNK: 'Punk',
  INDIE: 'Indie',
  ELECTRONICA: 'Electronica',
  HIPHOP: 'Hip-Hop',
  RAP: 'Rap',
  SOUL: 'Soul',
  REGGAE: 'Reggae',
  BLUES: 'Blues',
  JAZZ: 'Jazz',
  COUNTRY: 'Country',
  FOLK: 'Folk',
  LATIN: 'Latin',
  CLASICA: 'Clasica',
  PHONK: 'Phonk',
  HOUSE: 'House',
  TECHNO: 'Techno',
  TRANCE: 'Trance',
  DRUM_AND_BASS: 'Drum & Bass',
  TRAP: 'Trap',
  DUBSTEP: 'Dubstep',
  FUNK: 'Funk',
  DISCO: 'Disco',
  RB: 'R&B',
  SKA: 'Ska',
  REGGAETON: 'Reggaeton',
  SALSA: 'Salsa',
  MERENGUE: 'Merengue',
  BACHATA: 'Bachata',
  CUMBIA: 'Cumbia',
  VALLENATO: 'Vallenato',
  OTROS: 'Otros',
}

module.exports = MusicGenre
